name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.10
  - numpy=1.19.5
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=23.3.1
  - pandas-profiling=3.6.3
  - pyarrow=2.0.0
  - pip:
      - wandb==0.10.21
      - protobuf==3.19.5