name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - numpy=1.19.5
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=23.3.1
  - pip:
      - wandb==0.10.21
      - protobuf==3.19.5
