name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - numpy=1.19.5
  - pyyaml=6.0.1
  - hydra-core=1.0.6
  - pip=23.3.1
  - pip:
      - wandb==0.10.21
      - protobuf==3.19.5