name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=1.14.1
  - numpy=1.19.5
  - ipython=8.12.3
  - notebook=6.2.0
  - jupyterlab=3.0.10
  - hydra-core=1.0.6
  - matplotlib=3.3.4
  - pandas=1.2.3
  - git=2.40.1
  - pip=23.3.1
  - pip:
      - wandb==0.10.21
      - protobuf==3.19.5
