name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - numpy=1.19.5
  - pip=23.3.1
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - pip:
      - wandb==0.10.21
      - protobuf==3.19.5
      - git+https://github.com/lujiangCassie/NYC_rental_prices.git#egg=wandb-utils&subdirectory=components
