name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - numpy=1.19.5
  - pip=23.3.1
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.3.4
  - pillow=10.1.0
  - pip:
      - wandb==0.10.21
      - protobuf==3.19.5
