name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.1
  - numpy=1.19.5
  - requests=2.28.2
  - mlflow=1.14.1
  - pip:
      - wandb==0.10.21
      - protobuf==3.19.5
      - git+https://github.com/lujiangCassie/NYC_rental_prices.git#egg=wandb-utils&subdirectory=components
